export const APPLICATION_COMMAND_IDS = [
  "file.new",
  "file.open",
  "file.save",
  "file.saveAs",
  "file.exportPng",
  "file.exportPngSequence",
  "file.exportSpriteSheet",
  "file.exportGif",
  "file.exportApng",
  "file.close",
  "edit.undo",
  "edit.redo",
  "edit.copy",
  "edit.cut",
  "edit.paste",
  "edit.delete",
  "select.all",
  "select.none",
  "sprite.cropToSelection",
  "sprite.canvasResize",
  "sprite.spriteResize",
  "sprite.convertToIndexed",
  "sprite.convertToRgba",
  "frame.add",
  "frame.duplicate",
  "frame.duplicateLinked",
  "frame.delete",
  "frame.moveLeft",
  "frame.moveRight",
  "frame.first",
  "frame.previous",
  "frame.next",
  "frame.last",
  "frame.setDuration",
  "cel.create",
  "cel.delete",
  "cel.duplicate",
  "cel.linkToPrevious",
  "cel.unlink",
  "animation.playPause",
  "animation.stop",
  "animation.setLoop",
  "animation.setOnce",
  "animation.setPingPong",
  "animation.toggleOnionSkin",
  "animation.onionSkinSettings",
  "tag.add",
  "tag.edit",
  "tag.delete",
  "timeline.zoomIn",
  "timeline.zoomOut",
  "view.zoomIn",
  "view.zoomOut",
  "view.zoom100",
  "view.zoomFit",
  "view.commandPalette",
  "view.setThemeSystem",
  "view.setThemeDark",
  "view.setThemeLight",
  "view.setUiScale",
  "view.resetLayout",
  "window.toggleTools",
  "window.toggleLayers",
  "window.toggleTimeline",
  "help.about",
  "tool.pencil",
  "tool.eraser",
  "tool.eyedropper",
  "tool.fill",
  "tool.line",
  "tool.rectangle",
  "tool.ellipse",
  "tool.selectionRect",
  "tool.move",
  "layer.add",
  "layer.delete",
  "layer.duplicate",
  "layer.addGroup",
  "layer.addTilemap",
  "layer.indent",
  "layer.outdent",
  "layer.mergeDown",
  "layer.mergeVisible",
  "layer.flattenGroup",
  "layer.flattenDocument",
  "layer.setBlendMode",
  "palette.addCurrent",
  "palette.delete",
  "palette.moveUp",
  "palette.moveDown",
  "palette.sortHue",
  "palette.sortSaturation",
  "palette.sortValue",
  "palette.sortLuminance",
  "palette.sortUsage",
  "palette.mergeDuplicates",
  "palette.removeUnused",
  "palette.compact",
  "palette.import",
  "palette.export",
  "brush.createFromSelection",
  "brush.managePresets",
  "brush.rotateClockwise",
  "brush.flipHorizontal",
  "brush.flipVertical",
  "brush.togglePixelPerfect",
  "symmetry.off",
  "symmetry.horizontal",
  "symmetry.vertical",
  "symmetry.both",
  "symmetry.resetAxes",
  "tileset.create",
  "tileset.import",
  "tileset.edit",
  "tileset.delete",
  "tool.tilePencil",
  "tool.tileEraser",
  "tool.tileEyedropper",
  "tool.tileFill",
  "tool.tileSelection",
  "tool.tileMove",
  "slice.add",
  "slice.edit",
  "slice.delete",
  "file.importAseprite",
  "file.exportTilemap",
  "recovery.open",
  "recovery.delete",
  "recovery.deleteAll",
  "plugin.manage",
  "plugin.install",
  "plugin.enable",
  "plugin.disable",
  "plugin.disableAll",
  "plugin.remove",
  "plugin.restart",
  "plugin.showPermissions",
  "plugin.clearStorage",
  "plugin.openLogs",
  "plugin.enterSafeMode",
  "plugin.exitSafeMode",
  "plugin.manageImporters",
  "plugin.manageExporters",
  "plugin.manageTools",
  "window.saveLayout",
  "window.manageLayouts",
  "window.exportLayout",
  "window.importLayout",
  "preferences.keybindings",
  "preferences.importKeybindings",
  "preferences.exportKeybindings",
  "preferences.resetKeybindings",
  "preferences.resetAll",
] as const;

export type ApplicationCommandId = (typeof APPLICATION_COMMAND_IDS)[number];

export const NATIVE_MENU_COMMAND_IDS = [
  "view.commandPalette",
  "file.new",
  "file.open",
  "file.save",
  "file.saveAs",
  "file.exportPng",
  "file.exportPngSequence",
  "file.exportSpriteSheet",
  "file.exportGif",
  "file.exportApng",
  "file.close",
  "edit.undo",
  "edit.redo",
  "edit.copy",
  "edit.cut",
  "edit.paste",
  "edit.delete",
  "select.all",
  "select.none",
  "sprite.cropToSelection",
  "sprite.canvasResize",
  "sprite.spriteResize",
  "frame.add",
  "frame.duplicate",
  "frame.duplicateLinked",
  "frame.delete",
  "frame.previous",
  "frame.next",
  "frame.setDuration",
  "cel.linkToPrevious",
  "cel.unlink",
  "animation.playPause",
  "animation.stop",
  "animation.toggleOnionSkin",
  "animation.onionSkinSettings",
  "tag.add",
  "tag.edit",
  "tag.delete",
  "timeline.zoomIn",
  "timeline.zoomOut",
  "view.zoomIn",
  "view.zoomOut",
  "view.zoom100",
  "view.zoomFit",
  "tool.pencil",
  "tool.eraser",
  "tool.eyedropper",
  "tool.fill",
  "tool.line",
  "tool.rectangle",
  "tool.ellipse",
  "tool.selectionRect",
  "tool.move",
  "layer.add",
  "layer.delete",
  "layer.duplicate",
  "view.setThemeSystem",
  "view.setThemeDark",
  "view.setThemeLight",
  "view.resetLayout",
  "window.toggleTools",
  "window.toggleLayers",
  "window.toggleTimeline",
  "help.about",
  "plugin.manage",
  "plugin.install",
  "plugin.enable",
  "plugin.disable",
  "plugin.disableAll",
  "plugin.remove",
  "plugin.restart",
  "plugin.showPermissions",
  "plugin.clearStorage",
  "plugin.openLogs",
  "plugin.enterSafeMode",
  "plugin.exitSafeMode",
] as const satisfies readonly ApplicationCommandId[];

export const DEFAULT_KEYBINDINGS = {
  "view.commandPalette": "CommandOrControl+Shift+P",
  "file.new": "CommandOrControl+N",
  "file.open": "CommandOrControl+O",
  "file.save": "CommandOrControl+S",
  "edit.undo": "CommandOrControl+Z",
  "edit.redo": "CommandOrControl+Shift+Z",
  "edit.copy": "CommandOrControl+C",
  "edit.cut": "CommandOrControl+X",
  "edit.paste": "CommandOrControl+V",
  "edit.delete": "Delete",
  "select.all": "CommandOrControl+A",
  "select.none": "CommandOrControl+Shift+A",
  "file.saveAs": "CommandOrControl+Shift+S",
  "file.close": "CommandOrControl+W",
  "view.zoomIn": "CommandOrControl+Plus",
  "view.zoomOut": "CommandOrControl+-",
  "view.zoom100": "CommandOrControl+0",
  "tool.pencil": "P",
  "tool.eraser": "E",
  "tool.eyedropper": "I",
  "tool.fill": "G",
  "tool.line": "L",
  "tool.rectangle": "R",
  "tool.ellipse": "Shift+O",
  "tool.selectionRect": "S",
  "tool.move": "M",
  "frame.add": "Alt+N",
  "frame.duplicate": "Alt+D",
  "frame.duplicateLinked": "Alt+Shift+D",
  "frame.delete": "Alt+Delete",
  "frame.previous": "[",
  "frame.next": "]",
  "frame.first": "Shift+[",
  "frame.last": "Shift+]",
  "animation.playPause": "Enter",
  "animation.stop": "Shift+Enter",
  "animation.toggleOnionSkin": "O",
  "tag.add": "CommandOrControl+Alt+T",
} as const satisfies Partial<Record<ApplicationCommandId, string>>;

export function findDuplicateKeybindings(
  keybindings: Readonly<Partial<Record<ApplicationCommandId, string>>>,
): string[] {
  const seen = new Map<string, ApplicationCommandId>();
  const duplicates = new Set<string>();
  for (const [commandId, keybinding] of Object.entries(keybindings)) {
    const normalized = keybinding.toLocaleLowerCase("en-US");
    if (seen.has(normalized)) duplicates.add(keybinding);
    else seen.set(normalized, commandId as ApplicationCommandId);
  }
  return [...duplicates];
}
