import { z } from "zod";

export const KEYBINDING_SCHEMA_VERSION = 1 as const;
export type KeybindingContext = "global" | "canvas" | "text-input";
export type KeybindingPreset = "suwol-default" | "minimal" | "classic-pixel-workflow";
export interface KeybindingEntry { readonly commandId: string; readonly shortcuts: readonly string[]; readonly context: KeybindingContext; }
export interface KeybindingSettings { readonly schemaVersion: typeof KEYBINDING_SCHEMA_VERSION; readonly preset: KeybindingPreset; readonly entries: readonly KeybindingEntry[]; }
export interface KeybindingConflict { readonly shortcut: string; readonly context: KeybindingContext; readonly commandIds: readonly string[]; }

const shortcutSchema = z.string().min(1).max(80).refine((value) => normalizeShortcut(value) === value, "Shortcut must be canonical."), entrySchema = z.object({ commandId: z.string().min(1).max(180), shortcuts: z.array(shortcutSchema).max(8), context: z.enum(["global", "canvas", "text-input"]) }).strict();
export const keybindingSettingsSchema = z.object({ schemaVersion: z.literal(KEYBINDING_SCHEMA_VERSION), preset: z.enum(["suwol-default", "minimal", "classic-pixel-workflow"]), entries: z.array(entrySchema).max(2_000) }).strict().superRefine((settings, context) => { const commands = new Set<string>(); settings.entries.forEach((entry, index) => { if (commands.has(entry.commandId)) context.addIssue({ code: "custom", path: ["entries", index, "commandId"], message: "Command keybinding entry is duplicated." }); commands.add(entry.commandId); }); });

export function normalizeShortcut(input: string): string { const aliases: Record<string, string> = { ctrl: "Ctrl", control: "Ctrl", cmd: "Meta", command: "Meta", meta: "Meta", alt: "Alt", option: "Alt", shift: "Shift", esc: "Escape", del: "Delete", return: "Enter", space: "Space" }, parts = input.trim().split("+").map((part) => part.trim()).filter(Boolean), modifiers = new Set<string>(), keys: string[] = []; for (const part of parts) { const normalized = aliases[part.toLowerCase()] ?? (part.length === 1 ? part.toUpperCase() : `${part.charAt(0).toUpperCase()}${part.slice(1).toLowerCase()}`); if (["Ctrl", "Meta", "Alt", "Shift"].includes(normalized)) modifiers.add(normalized); else keys.push(normalized); } if (keys.length !== 1) return ""; return [...["Ctrl", "Meta", "Alt", "Shift"].filter((modifier) => modifiers.has(modifier)), keys[0]].join("+"); }
export function formatShortcut(shortcut: string, platform: "windows" | "macos" | "linux"): string { if (platform !== "macos") return shortcut; return shortcut.replace(/Meta/g, "⌘").replace(/Ctrl/g, "⌃").replace(/Alt/g, "⌥").replace(/Shift/g, "⇧").replace(/\+/g, ""); }
export function keybindingWarnings(shortcut: string, context: KeybindingContext, platform: "windows" | "macos" | "linux" = "windows"): readonly string[] { const normalized = normalizeShortcut(shortcut), warnings: string[] = []; if (normalized === "") return ["Shortcut is invalid."]; const parts = normalized.split("+"), key = parts.at(-1) ?? "", hasModifier = parts.length > 1; if (!hasModifier && /^[A-Z0-9]$/.test(key)) warnings.push("Unmodified character shortcuts are unsafe while typing."); if (context === "text-input" && ["Escape", "Enter", "Delete"].includes(key)) warnings.push("Shortcut conflicts with text input behavior."); const reserved = platform === "windows" ? ["Alt+F4", "Ctrl+Alt+Delete", "Meta+L"] : platform === "macos" ? ["Meta+Q", "Meta+Space", "Meta+Tab"] : ["Alt+F4", "Ctrl+Alt+Delete"]; if (reserved.includes(normalized)) warnings.push("Shortcut is reserved by the operating system."); return warnings; }
export function findKeybindingConflicts(settings: KeybindingSettings): readonly KeybindingConflict[] { const map = new Map<string, string[]>(); for (const entry of settings.entries) for (const shortcut of entry.shortcuts) { const key = `${entry.context}\0${shortcut}`, commands = map.get(key) ?? []; commands.push(entry.commandId); map.set(key, commands); } return [...map].filter(([, commands]) => commands.length > 1).map(([key, commandIds]) => { const [context, shortcut] = key.split("\0"); return { context: context as KeybindingContext, shortcut: shortcut ?? "", commandIds }; }); }
export function parseKeybindingSettings(input: unknown): KeybindingSettings { const result = keybindingSettingsSchema.safeParse(input); if (!result.success) throw new Error("Keybinding settings JSON is invalid."); return result.data; }
export function resolveKeybindingConflict(settings: KeybindingSettings, commandId: string, shortcut: string, context: KeybindingContext, strategy: "replace" | "remove-existing" | "cancel"): KeybindingSettings { if (strategy === "cancel") return settings; const normalized = normalizeShortcut(shortcut); if (normalized === "") throw new Error("Shortcut is invalid."); const entries = settings.entries.map((entry) => ({ ...entry, shortcuts: [...entry.shortcuts] })); for (const entry of entries) if (entry.context === context && entry.commandId !== commandId) entry.shortcuts = entry.shortcuts.filter((value) => value !== normalized); let target = entries.find((entry) => entry.commandId === commandId); if (target === undefined) { target = { commandId, context, shortcuts: [] }; entries.push(target); } if (!target.shortcuts.includes(normalized)) target.shortcuts.push(normalized); return parseKeybindingSettings({ ...settings, entries }); }
export function serializeKeybindingSettings(settings: KeybindingSettings): string { return JSON.stringify(parseKeybindingSettings(settings), null, 2); }
