import { describe, expect, it } from "vitest";
import { overlayUpdateSchema, parsePluginPermission, pluginExportResultSchema, pluginImportResultSchema, pluginManifestSchema, pluginToolEventSchema, PLUGIN_API_VERSION } from "./index";

const manifest = { manifestVersion: 1 as const, id: "com.example.professional", name: "Professional", version: "1.0.0", apiVersion: "^1.1.0", engines: { suwolPixelStudio: ">=0.5.0" }, entry: "dist/main.js", permissions: ["file.import", "file.export", "ui.tool", "ui.overlay"], contributes: { importers: [{ id: "com.example.professional.importer", title: "Importer", extensions: [".safe"] }], exporters: [{ id: "com.example.professional.exporter", title: "Exporter", extensions: [".json"] }], tools: [{ id: "com.example.professional.tool", title: "Tool" }], overlays: [{ id: "com.example.professional.overlay", title: "Overlay", zOrder: "above-document" }] } };
describe("Plugin API 1.1", () => {
  it("keeps protocol v1 while adding backward-compatible 1.1 contributions", () => { expect(PLUGIN_API_VERSION).toBe("1.1.0"); expect(pluginManifestSchema.parse(manifest).contributes?.tools).toHaveLength(1); });
  it("requires contribution permissions and plugin namespace", () => { expect(pluginManifestSchema.safeParse({ ...manifest, permissions: [] }).success).toBe(false); expect(pluginManifestSchema.safeParse({ ...manifest, contributes: { tools: [{ id: "other.tool", title: "Bad" }] }, permissions: ["ui.tool"] }).success).toBe(false); });
  it("recognizes exact new capabilities without wildcard permission", () => { expect(parsePluginPermission("file.import")).toBe("file.import"); expect(parsePluginPermission("ui.overlay")).toBe("ui.overlay"); expect(parsePluginPermission("file.*")).toBeNull(); });
  it("rejects exporter traversal and over-sized overlays", () => { expect(pluginExportResultSchema.safeParse({ files: [{ relativePath: "../escape", data: new ArrayBuffer(1) }] }).success).toBe(false); expect(overlayUpdateSchema.safeParse({ overlayId: "com.example.professional.overlay", lifetimeMs: 1000, primitives: Array.from({ length: 1001 }, () => ({ kind: "text", position: { x: 0, y: 0 }, text: "x" })) }).success).toBe(false); });
  it("validates declarative importer and normalized tool events", () => { const result = { document: { name: "Imported", width: 1, height: 1, colorMode: "rgba", palette: [], frames: [{ durationMs: 100 }], layers: [{ id: "temp:layer", name: "Layer" }], cels: [{ layerId: "temp:layer", frameIndex: 0, x: 0, y: 0, width: 1, height: 1, format: "rgba8", pixels: new Uint8Array([1,2,3,255]).buffer }] }, warnings: [] }; expect(pluginImportResultSchema.safeParse(result).success).toBe(true); expect(pluginToolEventSchema.safeParse({ type: "pointerDown", strokeId: crypto.randomUUID(), position: { x: 1, y: 2 }, pressure: .5, modifiers: { shift: false, alt: false, primary: true }, layerId: "layer", frameId: "frame" }).success).toBe(true); });
});

