import { describe, expect, it } from "vitest";
import { EditorSession, hashSnapshot } from "@suwol/editor-core";
import { PluginOverlayUpdateGate, PluginToolStrokeBroker, createPluginRuntimeBootstrap, validateOverlayUpdate, validatePluginExportResult, validatePluginImportResult } from "./index";

describe("M5 plugin security boundaries", () => {
  it("removes direct GPU/DOM/network capabilities and routes tool execution in the Worker bootstrap", () => { const source = createPluginRuntimeBootstrap(); expect(source).toContain("OffscreenCanvas: { value: undefined }"); expect(source).toContain("fetch: { value: blocked }"); expect(source).toContain('message.event === "tool.execute"'); expect(source).toContain("message.payload?.input"); expect(source).not.toContain("document."); });
  it("validates importer buffers and indexed palette bounds", () => { const base = { document: { name: "Bad", width: 1, height: 1, colorMode: "indexed", transparentIndex: 0, palette: [[0,0,0,0]], frames: [{ durationMs: 100 }], layers: [{ id: "temp:layer", name: "Layer" }], cels: [{ layerId: "temp:layer", frameIndex: 0, x: 0, y: 0, width: 1, height: 1, format: "indexed8", pixels: Uint8Array.from([1]).buffer }] }, warnings: [] }; expect(() => validatePluginImportResult(base)).toThrow("palette"); });
  it("rejects exporter traversal before opaque destination write", () => expect(() => validatePluginExportResult({ files: [{ relativePath: "a/../../escape", data: new ArrayBuffer(1) }] })).toThrow());
  it("clips declarative overlays and rejects oversized preview buffers", () => { const update = validateOverlayUpdate({ overlayId: "com.example.overlay", lifetimeMs: 1000, primitives: [{ kind: "rect", rect: { x: -5, y: -5, width: 10, height: 10 }, style: { color: [255,255,255,255] } }] }, { width: 4, height: 4 }); expect(update.primitives[0]?.kind === "rect" && update.primitives[0].rect).toEqual({ x: 0, y: 0, width: 4, height: 4 }); expect(() => validateOverlayUpdate({ overlayId: "com.example.overlay", lifetimeMs: 1000, primitives: [{ kind: "imagePreview", rect: { x: 0, y: 0, width: 1, height: 1 }, pixels: new ArrayBuffer(5 * 1024 * 1024) }] }, { width: 4, height: 4 })).toThrow(); });
  it("commits one plugin tool stroke as one undo step and rolls cancellation back", () => { const session = EditorSession.create({ name: "Tool", layerName: "Layer", width: 4, height: 4 }), layer = session.model.layerOrder[0] ?? "", broker = new PluginToolStrokeBroker(session, "com.example.tool"), initial = hashSnapshot(session.snapshot()), strokeId = crypto.randomUUID(); broker.begin(strokeId, layer); broker.append(strokeId, { type: "pixels", points: [{ x: 1, y: 1 }, { x: 2, y: 2 }], rgba: [255,0,0,255] }); expect(broker.commit(strokeId)).toBe(true); expect(session.history.undoCount).toBe(1); expect(session.undo()).toBe(true); expect(hashSnapshot(session.snapshot())).toBe(initial); const cancelled = crypto.randomUUID(); broker.begin(cancelled, layer); broker.append(cancelled, { type: "pixels", points: [{ x: 0, y: 0 }], rgba: [0,0,0,255] }); broker.cancel(cancelled); expect(hashSnapshot(session.snapshot())).toBe(initial); });
  it("blocks late tool writes and throttles overlay updates", () => { const session = EditorSession.create({ name: "Tool", layerName: "Layer", width: 2, height: 2 }), layer = session.model.layerOrder[0] ?? "", broker = new PluginToolStrokeBroker(session, "com.example.tool"), strokeId = crypto.randomUUID(); broker.begin(strokeId, layer, 100); broker.append(strokeId, { type: "pixels", points: [{ x: 0, y: 0 }], rgba: [1,2,3,255] }, 101); broker.commit(strokeId, 102); expect(() => broker.append(strokeId, { type: "clear", points: [{ x: 0, y: 0 }] }, 103)).toThrow("not active"); const gate = new PluginOverlayUpdateGate(2, 1000); gate.enter(1000); gate.enter(1001); expect(() => gate.enter(1002)).toThrow("rate"); gate.enter(2001); });
});
